glib2 windows: use old p11-kit
Because 0.23.10 isn't cross buildable...

    common/runtime.c:40:17: fatal error: pwd.h: No such file or directory
    compilation terminated.