gtk3: call Gdk.init in gtk-demo/main.rb
Because the following error occurred (missing class type):

    ./main.rb:34:in `block in initialize': undefined method `state' for #<#<Class:0xb8e17a90>:0xb913e1ec ptr=0xb94ca6b8 own=true>
             from ./main.rb:384:in `call'
             from ./main.rb:384:in `main'
             from ./main.rb:384:in `<main>'

TODO: the following error still occurred
(Gdk::EventKey may be expected, but actual was Gdk::Event):

    ./main.rb:37:in `block in initialize': undefined method `state' for #<Gdk::Event:0xb94b7378 ptr=0xb8df4f18 own=true>
             from ./main.rb:387:in `call'
             from ./main.rb:387:in `main'
             from ./main.rb:387:in `<main>'