glib2: Use NUM2ULONG instead of NUM2UINT in GLib.format_size
    fixes #413

    Because following RangeError exception is thrown when GLib.format_size(1000 * 1000
    * 1000 * 5):

    ```log
    Error: test_5gb(TestGLibFileUtils::#format_size)
    : RangeError: integer 5000000000 too big to convert to `unsigned int'
    ruby-gnome2/glib2/test/test_file_utils.rb:34:in
    `format_size'
    ruby-gnome2/glib2/test/test_file_utils.rb:34:in
    `test_5gb'
         31:     end
         32:
         33:     def test_5gb
      => 34:       assert_equal("5.0 GB", GLib.format_size(1000 * 1000 * 1000 * 5))
         35:     end
         36:
         37:     sub_test_case "flags" do
    ```