glib2 windows: fix a cross compiling error
The error occurred in GnuTLS by MinGW-w64 3.0.0 and GCC 4.8.2.

    ../../gl/string.h:1002:1: error: expected unqualified-id before 'char'
     _GL_FUNCDECL_SYS (strtok_r, char *,
     ^
    ../../gl/string.h:1002:1: error: expected ')' before 'char'
    ../../gl/string.h:1002:1: error: expected ')' before 'char'
    ../../gl/string.h:1002:1: error: expected initializer before 'char'
    make[4]: *** [ex-cxx.o] Error 1

The error fixed, but I don't understand the reason of the problem...

TODO: libglib-2.0-0.dll depends on the libralies but they are not found.

    * libgcc_s_sjlj-1.dll
    * libwinpthread-1.dll