glib2: fix handling of 64 bits FIXNUM variant initialization
This fixes the following error:

irb(main):001:0> require 'glib2'
=> true
irb(main):002:0> GLib::Variant.new(333222111000)
RangeError: integer 333222111000 too big to convert to `int'
            from (irb):2:in `initialize'
            from (irb):2:in `new'
            from (irb):2
            from /usr/bin/irb:11:in `<main>'