vte3: vte3-no-gi/ext/vte3/ -> vte3-no-gi/ext/vte3-no-gi
Because following error occurred after
`bundle exec rake configure && make`:

```log
compiling rbvte.c
In file included from rbvte.c:21:
./rbvte3private.h:10:10: fatal error: 'rbgtk3.h' file not found
 #include <rbgtk3.h>
         ^
		 1 error generated.
make[2]: *** [rbvte.o] Error 1
make[1]: *** [all] Error 2
make: *** [all-vte3-no-gi] Error 2
rake aborted!
```

This change makes always vte3-no-gi putting into `ingore_modules`.