[gtk2] fix require failure with GTK+ < 2.14.
[ruby-gnome2-devel-en] NameError: undefined method `color_selection' for class `Gtk::ColorSelectionDialog'
Reported by grant schoep. Thanks!!!