clutter-gstreamer test: use ENV["CI"] for omitted condition
Because the following error occurred on Travis CI:

    ===============================================================================
    Error: test_init(ClutterGstTest)
    GLib::Error: Requiring namespace 'GstBase' version '0.10', but '1.0' is already loaded
    /home/travis/build/ruby-gnome2/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:35:in `require'
    /home/travis/build/ruby-gnome2/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:35:in `load'
    /home/travis/build/ruby-gnome2/ruby-gnome2/clutter-gstreamer/lib/clutter-gst.rb:49:in `init'
    /home/travis/build/ruby-gnome2/ruby-gnome2/clutter-gstreamer/lib/clutter-gst.rb:33:in `const_missing'
    /home/travis/build/ruby-gnome2/ruby-gnome2/clutter-gstreamer/test/clutter-gstreamer-test-utils.rb:24:in `later_version?'
    /home/travis/build/ruby-gnome2/ruby-gnome2/clutter-gstreamer/test/clutter-gstreamer-test-utils.rb:33:in `only_clutter_gstreamer_version'
    /home/travis/build/ruby-gnome2/ruby-gnome2/clutter-gstreamer/test/test-clutter-gst.rb:21:in `test_init'
         18:   include ClutterGStreamerTestUtils
         19:
         20:   def test_init
      => 21:     only_clutter_gstreamer_version(2, 0, 0)
         22:     assert_nothing_raised do
         23:       ClutterGst.init
         24:     end
    ===============================================================================