clutter-gtk: add a check for duplicate Clutter.init
Because the following error occurred:

    % ruby -r clutter-gtk -e "Clutter::Color; ClutterGtk::Actor"
    /.../clutter-gtk-2.1.0/lib/clutter-gtk.rb:44:in `init': undefined method `init' for Clutter:Module (NoMethodError)
            from /.../clutter-gtk-2.1.0/lib/clutter-gtk.rb:33:in `const_missing'
            from -e:1:in `<main>'